name: Build_Pipeline_$(Date:yyyy-MM-dd)_v$(Rev:rr)

trigger:
  batch: true
  branches:
    include:
    - '*'
    exclude: 
    - main 
  paths:
    include:
      - 'project-3'

pr:
  branches:
    include: 
    - main
  paths:
    include:
      - 'project-3'

variables:
- name: systm.debug
  value: 'true'
- group: 'service-connection'
- name: Pipeline-Agent
  value: 'ubuntu-latest'

  # Using build_template pipeline in submodules
stages:
- template: templates/build_template.yml
  parameters:
    SourceDirectory: 'infrastructure/network'   # change directory to network
    infrastructure: 'Network'
    tfplan: 'network.tflan'
    BlobName: 'network.tfstate'

- template: templates/build_template.yml
  parameters:
    SourceDirectory: 'infrastructure/compute'   # change directory to compute
    infrastructure: 'Compute'
    tfplan: 'compute.tflan'
    BlobName: 'compute.tfstate'

- template: templates/build_template.yml
  parameters:
    SourceDirectory: 'infrastructure/routes'    # change directory to routes 
    infrastructure: 'Routes'
    tfplan: 'routes.tflan'
    BlobName: 'routes.tfstate'
 