name: 'Build and Release Pipelines $(Date:yyyy-MM-dd)_v$(Rev:rr)'

pr: none

trigger:
  branches:
    include:
    - main
    - dev
  paths:
    include:
    - project-2
    exclude:
    - project-2/cleanup-pipelines.yml
    - terraform-cmd.yml

variables:
- group: 'service-connection'
- name: system.debug
  value: 'true'
- name: RGName
  value: "rg-ADO-2"            
- name: StorageAccName
  value: "mystorageacct16425"  
- name: ContainerName
  value: "storage-container"         
- name: ADO-Environment
  value: "Staging"
- name: Pipeline-Agent
  value: 'My Agents'
- name: SKIPPED_CHECKS
  value: 'CKV_AZURE_183,CKV2_AZURE_40,CKV2_AZURE_41,CKV2_AZURE_33,CKV2_AZURE_1,CKV2_AZURE_38,CKV_AZURE_206'

  # Using build_template or ci_template pipeline based on branch condition
stages: 
- ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:  
  - template: templates/release_template.yml
    parameters:
      SourceDirectory: 'project-2'   
      TerraformDirectory: 'project-2/infra'
      infrastructure: 'ServiceEndpoint'
      tfplan: 'serviceEP.tfplan'
      BlobName: 'serviceEP.tfstate'
- ${{ else }}:
  - template: templates/build_template.yml
    parameters:
      SourceDirectory: 'project-2'   
      TerraformDirectory: 'project-2/infra'
      infrastructure: 'ServiceEndpoint'
      tfplan: 'serviceEP.tfplan'
      BlobName: 'serviceEP.tfstate'
     

 