name: 'Terraform state command'

trigger: none

pr: none

variables:
- group: 'service-connection'
- name: system.debug
  value: 'true'
- name: Pipeline-Agent
  value: 'My Agents'
- name: BlobName
  value: 'serviceEP.tfstate'
- name: system.debug
  value: 'true'
- name: RGName
  value: "rg-ADO-2"            
- name: StorageAccName
  value: "mystorageacct16425"  
- name: ContainerName
  value: "storage-container"    
- name: TerraformDirectory
  value: 'project-2/infra'

jobs:
- job:
  pool: $(Pipeline-Agent)    

  steps:
  - template: 'templates/installs.yml'
  - checkout: self
    clean: true

  - bash: |
      terraform init -input=false -lock=false \
        -backend-config="resource_group_name=$(RGName)" \
        -backend-config="storage_account_name=$(StorageAccName)" \
        -backend-config="container_name=$(ContainerName)" \
        -backend-config="key=$(BlobName)" \
        -backend-config="use_azuread_auth=true"
      terraform state list -state=$(BlobName)
      echo -e "Number of resources:\t"
      terraform state list -state=$(BlobName) | wc -l
    env:
      ARM_CLIENT_ID: $(SPN2-client-id)
      ARM_TENANT_ID: $(SPN2-tenant-id)
      ARM_CLIENT_SECRET: $(SPN2-client-secret)
      ARM_SUBSCRIPTION_ID: $(SPN2-subscription-id)
    workingDirectory: $(TerraformDirectory)
    displayName: 'terraform state list'