name: 'Build and Release Pipeline $(Date:yyyy-MM-dd)_v$(Rev:rr)'

pr: none

trigger:
  branches:
    include:
    - '*'
  paths:
    include:
    - project-3
    exclude:
    - project-3/cleanup-pipelines.yml

variables:
- group: 'service-connection'
- name: systm.debug
  value: 'true'
- name: RGName
  value: "rg-ADO-2"            
- name: StorageAccName
  value: "mystorageacct16425"  
- name: ContainerName
  value: "storage-container"         
- name: ADO-Environment
  value: "Staging"
- name: Pipeline-Agent
  value: 'My Agents'

  # Using build_template or ci_template pipeline based on branch condition
stages: 
- ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:  
  - template: templates/build_template.yml
    parameters:
      SourceDirectory: 'project-3/infra'   
      infrastructure: 'ServiceEndpoint'
      tfplan: 'serviceEP.tfplan'
      BlobName: 'serviceEP.tfstate'
- ${{ else }}:
  - template: templates/ci_template.yml
    parameters:
      SourceDirectory: 'project-3/infra'   
      infrastructure: 'ServiceEndpoint'
      tfplan: 'serviceEP.tfplan'
      BlobName: 'serviceEP.tfstate'
     

 