name: Build_Pipeline_$(Date:yyyy-MM-dd)_v$(Rev:rr)

trigger:
  batch: true
  branches:
    include:
    - '*'
    exclude: 
    - main 
  paths:
    include:
      - 'project-3'

pr:
  branches:
    include: 
    - main
  paths:
    include:
      - 'project-3'

variables:
- group: 'service-connection'
- name: systm.debug
  value: 'true'
- name: RGName
  value: "rg-ADO-2"            
- name: StorageAccName
  value: "mystorageacct16425"  
- name: ContainerName
  value: "storage-container"         
- name: ADO-Environment
  value: "Staging"
- name: Pipeline-Agent
  value: 'My Agents'

  # Using build_template pipeline in submodules
stages:
- template: templates/build_template.yml
  parameters:
    SourceDirectory: 'infrastructure/network'   # change directory to network
    infrastructure: 'Network'
    tfplan: 'network.tflan'
    BlobName: 'network.tfstate'

- template: templates/build_template.yml
  parameters:
    SourceDirectory: 'infrastructure/compute'   # change directory to compute
    infrastructure: 'Storage'
    tfplan: 'storage.tflan'
    BlobName: 'storage.tfstate'

- template: templates/build_template.yml
  parameters:
    SourceDirectory: 'infrastructure/routes'    # change directory to routes 
    infrastructure: 'Compute'
    tfplan: 'compute.tflan'
    BlobName: 'compute.tfstate'
 