name: 'Build and Release Pipeline $(Date:yyyy-MM-dd)_v$(Rev:rr)'

# trigger:
#   batch: true
#   branches:
#     include:
#     - '*'
#     exclude: 
#     - main 
#   paths:
#     include:
#       - 'project-3'

pr:
  branches:
    include: 
    - main
  paths:
    include:
      - 'project-3'

variables:
- group: 'service-connection'
- name: systm.debug
  value: 'true'
- name: RGName
  value: "rg-ADO-2"            
- name: StorageAccName
  value: "mystorageacct16425"  
- name: ContainerName
  value: "storage-container"         
- name: ADO-Environment
  value: "Staging"
- name: Pipeline-Agent
  value: 'My Agents'

  # Using build_template or ci_template pipeline based on branch condition in submodules
stages: 
- ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:  
  - template: templates/build_template.yml
    parameters:
      SourceDirectory: 'project-3/infra/network'   # change directory to network
      infrastructure: 'Network'
      tfplan: 'network.tfplan'
      BlobName: 'network.tfstate'
- ${{ else }}:
  - template: templates/ci_template.yml
    parameters:
      SourceDirectory: 'project-3/infra/network'   # change directory to network
      infrastructure: 'Network'
      tfplan: 'network.tfplan'
      BlobName: 'network.tfstate'
     
- ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:  
  - template: templates/build_template.yml
    parameters:
      SourceDirectory: 'project-3/infra/storage'   # change directory to storage
      infrastructure: 'Storage'
      tfplan: 'storage.tfplan'
      BlobName: 'storage.tfstate'
- ${{ else }}:
  - template: templates/ci_template.yml
    parameters:
      SourceDirectory: 'project-3/infra/storage'   # change directory to storage
      infrastructure: 'Storage'
      tfplan: 'storage.tfplan'
      BlobName: 'storage.tfstate'
    
- ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:  
  - template: templates/build_template.yml
    parameters:
      SourceDirectory: 'project-3/infra/compute'    # change directory to compute
      infrastructure: 'Compute'
      tfplan: 'compute.tfplan'
      BlobName: 'compute.tfstate'
- ${{ else }}:
  - template: templates/ci_template.yml
    parameters:
      SourceDirectory: 'project-3/infra/compute'    # change directory to compute
      infrastructure: 'Compute'
      tfplan: 'compute.tfplan'
      BlobName: 'compute.tfstate'
 