stages:
- stage: Build_${{parameters.infrastructure}}
  displayName: '${{parameters.SourceDirectory}} Build Stage'
  pool: $(Pipeline-Agent)
  
  jobs:
  - job: tfplan_scan_publish
    timeoutInMinutes: 10
    workspace:
      clean: all
    steps:
    - checkout: self
    - template: checkov-terraform_install.yml

    - bash: |
        checkov -d '$(Build.SourcesDirectory)/project-3' --quiet --deep-analysis \
          --enable-secret-scan-all-files --framework azure_pipelines
      displayName: 'scan azure pipelines'
      workingDirectory: '$(Build.SourcesDirectory)/project-3' 
      continueOnError: false
      condition: eq(variables['Build.SourceBranchName'], 'main')

    - bash: | 
        terraform init -input=false \
          -backend-config="resource_group_name=$(RGName)" \
          -backend-config="storage_account_name=$(StorageAccName)" \
          -backend-config="container_name=$(ContainerName)" \
          -backend-config="key=${{parameters.BlobName}}" \
          -backend-config="use_azuread_auth=true"
        terraform validate
        terraform plan -out='${{parameters.tfplan}}' -lock=false -input=false 
      env:
        ARM_CLIENT_ID: $(SPN2-client-id)
        ARM_TENANT_ID: $(SPN2-tenant-id)
        ARM_CLIENT_SECRET: $(SPN2-client-secret)
        ARM_SUBSCRIPTION_ID: $(SPN2-subscription-id)
      workingDirectory: ${{parameters.SourceDirectory}}
      displayName: 'terraform validate and plan'
      continueOnError: false

    - bash: |
        terraform show -json ${{parameters.tfplan}} | jq > '${{parameters.tfplan}}.json'
        checkov -f '${{parameters.tfplan}}.json' --output sarif --quiet \
          --enable-secret-scan-all-files --deep-analysis --framework terraform_plan
      displayName: 'output tfplan.json file and scan'
      workingDirectory: ${{parameters.SourceDirectory}}
      continueOnError: true

    - bash: mkdir Artifacts && mv 'results.sarif' '${{parameters.tfplan}}.json' Artifacts
      displayName: 'move results scan into Artifacts folder'
      workingDirectory: ${{parameters.SourceDirectory}}
      
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '${{parameters.SourceDirectory}}/Artifacts'
        artifact: '${{parameters.tfplan}}-artifact' # artifactName
        publishLocation: 'pipeline' # upload artifact to pipeline
      displayName: 'Publishing artifact'
    continueOnError: false  
   
- stage: Deploy_${{parameters.infrastructure}}
  condition: eq(variables['Build.SourceBranchName'], 'main')
  displayName: '${{parameters.SourceDirectory}} Deploy Stage'
  pool:
    name: $(Pipeline-Agent)

  jobs:
  - deployment: apply
    workspace:
      clean: all
    environment: $(ADO-Environment)        
    strategy:
      runOnce:
        deploy:
          steps:
          - download: none
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              artifactName: '${{parameters.tfplan}}-artifact'
              targetPath: '${{parameters.SourceDirectory}}'
            displayName: 'Downloading artifact'

          - template: checkov-terraform_install.yml
          
          - bash: |
              chmod -R a+x .terraform/*
              terraform init -input=false \
                -backend-config="resource_group_name=$(RGName)" \
                -backend-config="storage_account_name=$(StorageAccName)" \
                -backend-config="container_name=$(ContainerName)" \
                -backend-config="key=${{parameters.BlobName}}" \
                -backend-config="use_azuread_auth=true"
              terraform apply -auto-approve -input=false '-lock-timeout=2m' '${{parameters.tfplan}}' 
            env:
              ARM_CLIENT_ID: $(SPN2-client-id)
              ARM_TENANT_ID: $(SPN2-tenant-id)
              ARM_CLIENT_SECRET: $(SPN2-client-secret)
              ARM_SUBSCRIPTION_ID: $(SPN2-subscription-id)
            displayName: 'terraform apply'
            workingDirectory: ${{parameters.SourceDirectory}}
            