stages:
- stage: Build_${{parameters.infrastructure}}
  displayName: '${{parameters.SourceDirectory}} Build Stage'
  pool:
    vmImage: $(Pipeline-Agent)

  jobs:
  - job: tfvalidate
    continueOnError: false
    condition: ne(variables['Build.SourceBranchName'], 'main')
    steps:
    - checkout: self
    - template: checkov-terraform_install.yml

    - bash: |
        terraform init -input=false \
          -backend-config="resource_group_name=$(RGName)" \
          -backend-config="storage_account_name=$(StorageAccName)" \
          -backend-config="container_name=$(ContainerName)" \
          -backend-config="key=${{parameters.BlobName}}" \
          -backend-config="use_azuread_auth=true"
        terraform fmt && terraform validate  
      env:
        ARM_CLIENT_ID: $(SPN2-client-id)
        ARM_TENANT_ID: $(SPN2-tenant-id)
        ARM_CLIENT_SECRET: $(SPN2-client-secret)
        ARM_SUBSCRIPTION_ID: $(SPN2-subscription-id)
      displayName: 'terraform fmt and validate'
      workingDirectory: ${{parameters.SourceDirectory}}

  - job: tfplan_scan_publish
    dependsOn: tfvalidate
    condition: succeeded()
    steps:
    - checkout: self
    - template: checkov-terraform_install.yml

    - bash: | 
        terraform init -input=false \
          -backend-config="resource_group_name=$(RGName)" \
          -backend-config="storage_account_name=$(StorageAccName)" \
          -backend-config="container_name=$(ContainerName)" \
          -backend-config="key=${{parameters.BlobName}}" \
          -backend-config="use_azuread_auth=true"
        terraform plan -out='${{parameters.tfplan}}' -lock=false -input=false 

        terraform show -json ${{parameters.tfplan}} | jq > {{parameters.tfplan}}.json
        checkov -d $(Pipeline.Workspace) --output sarif --quiet \
          --skip-check CKV2_AZURE_39,CKV2_AZURE_31,CKV_AZURE_50 \
          --enable-secret-scan-all-files --deep-analysis
      env:
        ARM_CLIENT_ID: $(SPN2-client-id)
        ARM_TENANT_ID: $(SPN2-tenant-id)
        ARM_CLIENT_SECRET: $(SPN2-client-secret)
        ARM_SUBSCRIPTION_ID: $(SPN2-subscription-id)
        TF_VAR_hub-sshkey: $(hub-sshkey)
        TF_VAR_hub-sshkey-pub: $(hub-sshkey-pub)
        TF_VAR_sp1-sshkey: $(sp1-sshkey)
        TF_VAR_sp1-sshkey-pub: $(sp1-sshkey-pub)
        TF_VAR_sp2-sshkey: $(sp2-sshkey)
        TF_VAR_sp2-sshkey-pub: $(sp2-sshkey-pub)
        TF_VAR_mypublic-ip: $(mypublic-ip)
      workingDirectory: ${{parameters.SourceDirectory}}
      displayName: 'Plan and scan terraform files and pipeline'
      continueOnError: false
    
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: $(Pipeline.Workspace)
        artifact: '${{parameters.tfplan}}-artifact' # artifactName
        publishLocation: 'pipeline' # upload artifact to pipeline
      displayName: 'Publishing artifact'
    continueOnError: false  
   
- stage: Deploy_${{parameters.infrastructure}}
  condition: eq(variables['Build.SourceBranchName'], 'main')
  displayName: '${{parameters.SourceDirectory}} Deploy Stage'
  pool:
    vmImage: $(Pipeline-Agent)

  jobs:
  - deployment: apply
    environment: $(ADO-Environment)        
    strategy:
      runOnce:
        deploy:
          steps:
          - download: none
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              artifactName: '${{parameters.tfplan}}-artifact'
              targetPath: '$(Build.SourcesDirectory)'
            displayName: 'Downloading artifact'

          - template: checkov-terraform_install.yml
          
          - bash: |
              chmod -R a+x .terraform/*
              terraform init -input=false \
                -backend-config="resource_group_name=$(RGName)" \
                -backend-config="storage_account_name=$(StorageAccName)" \
                -backend-config="container_name=$(ContainerName)" \
                -backend-config="key=${{parameters.BlobName}}" \
                -backend-config="use_azuread_auth=true"
              terraform apply -auto-approve -input=false '-lock-timeout=2m' '${{parameters.tfplan}}' 
            env:
              ARM_CLIENT_ID: $(SPN2-client-id)
              ARM_TENANT_ID: $(SPN2-tenant-id)
              ARM_CLIENT_SECRET: $(SPN2-client-secret)
              ARM_SUBSCRIPTION_ID: $(SPN2-subscription-id)
            displayName: 'terraform apply'
            workingDirectory: ${{parameters.SourceDirectory}}