name: 'Build and Release Pipelines $(Date:yyyy-MM-dd)_v$(Rev:rr)'

pr: none

trigger: none
  # branches:
  #   include:
  #   - dev
  #   - main
  # paths:
  #   include:
  #   - project-4/*
  #   - '.github/workflows/project-4-tf-docs.yml'
  # tags: 
  #   include:
  #   - '*'
    
variables:
- group: 'linux-vmss'  
- group: 'password' 
- group: 'service-connection'
- name: system.debug
  value: 'true'
- name: RGName
  value: "rg-ADO-2"            
- name: StorageAccName
  value: "mystorageacct16425"  
- name: ContainerName
  value: "storage-container"         
- name: ADO_Environment
  value: "Staging"
- name: Pipeline_Agent
  value: 'My Agents'
- name: SKIPPED_CHECKS
  value: 'CKV_AZURE_183,CKV_AZURE_179,CKV_AZURE_97,CKV_AZURE_177'

  # Using build_template or ci_template pipeline based on branch condition
stages: 
- ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:  
  - template: templates/release_template.yml
    parameters:  
      TerraformDirectory: 'project-4'
      infrastructure: 'LoadBalancer'
      tfplan: 'lb.tfplan'
      BlobName: 'lb.tfstate'
- ${{ else }}:
  - template: templates/build_template.yml
    parameters: 
      TerraformDirectory: 'project-4'
      infrastructure: 'LoadBalancer'
      tfplan: 'lb.tfplan'
      BlobName: 'lb.tfstate'
     

 