name: 'Build and Release Pipelines $(Date:yyyy-MM-dd)_v$(Rev:rr)'

pr: none

trigger: 
  branches:
    include:
    - main
    - dev
  paths:
    include:
    - project-4
    exclude:
    - project-4/cleanup-pipelines.yml
    
variables:
- group: 'password'
- group: 'sshkeys'  
- group: 'service-connection'
- name: system.debug
  value: 'true'
- name: RGName
  value: "rg-ADO-2"            
- name: StorageAccName
  value: "mystorageacct16425"  
- name: ContainerName
  value: "storage-container"         
- name: ADO-Environment
  value: "Staging"
- name: Pipeline-Agent
  value: 'My Agents'
- name: SKIPPED_CHECKS
  value: ''

  # Using build_template or ci_template pipeline based on branch condition
stages: 
- ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:  
  - template: templates/release_template.yml
    parameters:  
      TerraformDirectory: 'project-4'
      infrastructure: 'LoadBalancer'
      tfplan: 'lb.tfplan'
      BlobName: 'lb.tfstate'
- ${{ else }}:
  - template: templates/build_template.yml
    parameters: 
      TerraformDirectory: 'project-4'
      infrastructure: 'LoadBalancer'
      tfplan: 'lb.tfplan'
      BlobName: 'lb.tfstate'
     

 