name: 'Decommission-Pipeline $(Date:yyyy-MM-dd)_v$(Rev:rr)'

trigger: none

pr: none

variables:
- group: 'password'
- group: 'service-connection'
- group: 'sshkeys'
- name: system.debug
  value: 'true'
- name: RGName
  value: "rg-ADO-2"            
- name: StorageAccName
  value: "mystorageacct16425"  
- name: ContainerName
  value: "storage-container"         
- name: ADO-Environment
  value: "Staging"
- name: Pipeline-Agent
  value: 'My Agents'
- name: stateFile
  value: 'lb.tfstate'

stages:
- stage: 'Destroy_Resources' 
  displayName: 'Destroy resoures'
  pool: $(Pipeline-Agent)
  
  jobs:
  - job:
    workspace:
      clean: all
    steps:
    - checkout: self
      clean: true
    - template: 'templates/installs.yml'

    - bash: | 
        terraform init -upgrade -reconfigure -input=false -lock=false \
          -backend-config="resource_group_name=$(RGName)" \
          -backend-config="storage_account_name=$(StorageAccName)" \
          -backend-config="container_name=$(ContainerName)" \
          -backend-config="key=$(stateFile)" \
          -backend-config="use_azuread_auth=true"
        terraform destroy -auto-approve -input=false '-lock-timeout=1m'
      env:
        ARM_CLIENT_ID: $(SPN2-client-id)
        ARM_TENANT_ID: $(SPN2-tenant-id)
        ARM_CLIENT_SECRET: $(SPN2-client-secret)
        ARM_SUBSCRIPTION_ID: $(SPN2-subscription-id)
        TF_VAR_vm_password: $(vm_password)
        TF_VAR_hub-sshkey-public: $(hub-sshkey-pub)
      workingDirectory: 'project-4'
      displayName: 'terraform destroy'
    